In [1]:
import numpy as np

In [2]:
m = [1, 2, 3]
n = [4, 5, 6]
m + n

[1, 2, 3, 4, 5, 6]

In [3]:
a = np.arange(6)
b = np.arange(6)

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
b

array([0, 1, 2, 3, 4, 5])

In [6]:
a + b

array([ 0,  2,  4,  6,  8, 10])

In [7]:
a - b

array([0, 0, 0, 0, 0, 0])

In [8]:
a * b

array([ 0,  1,  4,  9, 16, 25])

In [9]:
a / b

<ipython-input-9-d8e10abd5ab6>:1: RuntimeWarning: invalid value encountered in true_divide
  a / b


array([nan,  1.,  1.,  1.,  1.,  1.])

In [10]:
a = np.array([[1, 2]])
b = np.array([[1], [2]])

In [11]:
a

array([[1, 2]])

In [12]:
b

array([[1],
       [2]])

In [13]:
a.shape

(1, 2)

In [14]:
b.shape

(2, 1)

In [15]:
a + b

array([[2, 3],
       [3, 4]])

In [16]:
x = np.array(np.random.random(10))
x

array([0.51648858, 0.01331536, 0.5671455 , 0.83719826, 0.04668606,
       0.40240282, 0.88530928, 0.94524536, 0.70043607, 0.92891248])

In [17]:
x.shape

(10,)

In [18]:
x.reshape(2, 5)[0.516488

array([[0.51648858, 0.01331536, 0.5671455 , 0.83719826, 0.04668606],
       [0.40240282, 0.88530928, 0.94524536, 0.70043607, 0.92891248]])

In [19]:
np.random.random(10)

array([0.11857342, 0.91516245, 0.15729468, 0.10978092, 0.07863866,
       0.80418105, 0.23027358, 0.50880047, 0.90223983, 0.0220472 ])