In [10]:
import random

In [15]:
random.random()

0.05098379102044681

In [1]:
import numpy as np

In [20]:
# Return random floats in the half-open interval [0.0, 1.0).
# Alias for `random_sample` to ease forward-porting to the new random API.
a = np.random.random([3, 4])
print(a)

[[0.78917861 0.71893546 0.29657963 0.03277587]
 [0.35979887 0.93878372 0.25748795 0.68550628]
 [0.10742468 0.03264172 0.19230711 0.68308267]]


In [9]:
np.random.random()

0.11562079058741648

In [21]:
a = np.random.random_sample([2, 4])
print(a)

[[0.73211531 0.64798346 0.18738285 0.75783856]
 [0.34623691 0.10929117 0.12264166 0.91798437]]


In [26]:
# 정규분포의 난수 생성
b = np.random.randn(2)
print(b)
b = np.random.randn(2, 3)
print(b)
b = np.random.randn(3, 4)
print(b)

[-0.68212158 -0.93189189]
[[ 0.19145194  1.3933299   0.46544384]
 [-0.31760144  1.19570829 -0.14096653]]
[[-0.23370598  0.82782923 -0.48558901  0.62291088]
 [-0.41572265 -1.96932924 -1.5713652  -1.1222357 ]
 [ 0.65079216 -1.44063609  0.07546726  1.37430404]]


In [28]:
np.random.randn?

In [29]:
np.random.randn()

0.6763515757110231

In [30]:
# 값이 모두 1인 텐서
c = np.ones(3)
print(c)

[1. 1. 1.]


In [31]:
# 값이 모두 0인 텐서
c = np.zeros((2, 3))
print(c)
c = np.zeros([3, 4])
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
