In [1]:
import numpy as np

# [0, 1) 난수 생성
a = np.random.random((2, 3))
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[0.85300728 0.74684952 0.70700658]
 [0.42248166 0.98854076 0.75163151]]


In [3]:
b = a.reshape(3, 2)
print(b)

[[0.85300728 0.74684952]
 [0.70700658 0.42248166]
 [0.98854076 0.75163151]]


In [17]:
a.reshape(3, 2)
a

array([[0.85300728, 0.74684952, 0.70700658],
       [0.42248166, 0.98854076, 0.75163151]])

In [18]:
# 정규분포의 난수 생성
c = np.random.randn(3, 4)
print(c.reshape(2, 6))

# 값이 모두 1인 텐서
d = np.ones((4, 5))
print(d.reshape(2, 5, 2))

# 값이 모두 0인 텐서
e = np.zeros((3, 4))
print(e.reshape(2, 3, 2))

[[ 0.82922164  0.63990773  0.7145641   0.54532787 -0.83172377 -0.07443635]
 [-0.66979845  1.27526755  1.08423577 -2.40552381 -0.43372868  0.30432513]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [19]:
d = np.ones((4, 5))
print(d.reshape(2, 5, 2))

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [20]:
 d.reshape((1, 2, 5, 2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [21]:
e = np.zeros((3, 4))
print(e.reshape(2, 3, 2))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [23]:
e.reshape(1, 1, 1, 2, 3, 2)

array([[[[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]]]]])