In [5]:
# http://riseshia.github.io/2017/01/30/numpy-tutorial-with-code.html

import numpy as np

a = np.arange(12) # array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
type(a)

numpy.ndarray

In [4]:
type(list(range(12)))

list

In [7]:
b = a.reshape(4, 3) # 변환된 행렬을 반환
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
a.resize((3, 4)) # 자체를 변환함
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
a.flatten()
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
b = a.ravel()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
b = a.T # 전치 행렬
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [16]:
a.shape = 2, 6 # 파괴적
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [19]:
a.shape
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b = a.reshape(2, -1) # 변환된 행렬을 반환
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
